version: '3.7'
services:
  app:
    environment: 
          SPRING_DATASOURCE_URL: jdbc:mysql://contactdb.co5uetfpyg2p.us-east-1.rds.amazonaws.com:3306/sys?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
          SPRING_DATASOURCE_USERNAME: MasterAdmin
          SPRING_DATASOURCE_PASSWORD: Nizami242001!
    container_name: pbserver
    build:
        context: ./API
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # restart: always
    networks:
        - backend
        - frontend
    
  app-client:
    container_name: frontpb
    build:
      context: ./pbfront
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    # restart: always
    depends_on:
      - app
    networks:
      - frontend
networks:
  backend:
  frontend:   

